// src/lib/components/site-title.svelte
<script>
    export let siteTitle = "";
</script>

<div class="m-auto flex justify-center align-center logo-container">
    <h1 class="text-6xl font-pretendard font-black logo-text transition-all duration-200
        mt-half
        text-stroke before:transition-all ease-in-out hover:drop-shadow-xl">
        {siteTitle}
    </h1>
</div>

<style>
.logo-container{
    perspective: 1000px;
    perspective-origin: 0% 0%;
}

.logo-text{
    -webkit-text-stroke-width: 1px;
    text-align: center;
    transform-origin: 50% 50%;
    transform:
        rotateX(-25deg)
        rotateY(27deg)
        rotateZ(1deg);
}

.logo-text::before{
    content: 'TIL';
    -webkit-text-stroke-width: 2px;
    -webkit-text-stroke-color: rgb(0, 200, 200);
    position: absolute;
    right: 0.05em;
    top: -0.05em;
    z-index: -1;
    color: background;
}

.logo-text:hover{
    -webkit-text-stroke-width: 1px;
    filter: contrast(1.3);
    transform:
        translateX(-0.05em)
        translateY(-0.05em)
        rotateX(-25deg)
        rotateY(27deg)
        rotateZ(1deg);
}

.logo-text:hover::before{
    filter: contrast(1.3) hue-rotate(180deg);
    top: -0.07em;
    right: 0.07em;
}

.logo-text:active{
    filter: contrast(1.3) hue-rotate(20deg);
    transform:
        translateX(-0.1em)
        translateY(-0.1em)
        rotateX(-25deg)
        rotateY(27deg)
        rotateZ(1deg);
}

.logo-text:active::before{
    right: 0em;
    top: 0em;
}
</style>

// components/ui/title/site-title.tsx
import Link from "next/link";
import styles from './site-title.module.css'

export default function SiteTitle() {
    return (
        <Link href="/" className={`flex justify-center ${styles.container}`}>
            <h1 className={`text-4xl md:text-6xl font-black ${styles.text} 
                transition-all duration-200
                text-stroke before:transition-all 
                ease-in-out hover:drop-shadow-xl`}>
                TI
            </h1>
        </Link>
    )
}
