// src/routes/about/+page.svelte
<script>
    import { siteConfig } from "$lib/config"
</script>

<svelte:head>
    <title>{siteConfig.name} - about</title>
</svelte:head>

<div class="max-w-2xl self-center">
    <div class="flex flex-col gap-y-6">
        <h1 class="text-2xl font-semibold flex flex-grow">
            About Me
        </h1>
        <p class="leading-relaxed text-base text-wrap">
            I am a self-learner with interests ranging from user interface / experience, backend, to artificial intelligence. 
            Here, I am sharing my insights from my past-time tinkerings and readings. 
        </p>
        <p class="leading-relaxed text-base text-wrap">
            I occassionally research on topics in artificial intelligence (that is not necessarily related to large language models).
            I am currently based in Seoul, Korea with my black cat named ggoggam. 
            You can contact me via <a href="https://www.github.com/ggoggam" class="underline">Github</a>.
        </p>
    </div>
</div>

// src/app/about/page.tsx
import { Card, CardContent } from "@/components/ui/card";
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "@/components/ui/carousel";
import { getImages } from "@/lib/images";
import Image from "next/image";


export default async function AboutPage() {
  const imageFileNames = getImages()

  return (
    <div className="max-w-2xl mx-auto flex flex-col space-y-4 py-4 md:py-8">
      <h1 className="font-black text-4xl">ABOUT</h1>
      <p className="leading-relaxed">
        I am currently a research engineer at a medical artificial intelligence company (Lunit, if you are curious).
        Though my current main focus is on MLOps, I have a wide range of interests spanning from user interface / experience, backend, and computer science in general.
        My intention here is to share my insights and learnings from my past-time tinkerings and work. 
      </p>
      <p className='leading-relaxed pb-12'>
        I occassionally research on topics in artificial intelligence. 
        My recent research topic was on applying Bayesian methodologies to deep learning models, language model in particular.
        I am currently based in Seoul, South Korea with my black cat, ggoggam.
      </p>
      <div className="flex flex-col items-center justify-center">
        <Carousel className="w-full max-w-md">
        <CarouselContent>
          {imageFileNames.map((src, index) => (
            <CarouselItem key={index}>
              <div className="p-1">
                <Card>
                  <CardContent className="flex aspect-square items-center justify-center p-6">
                    <Image src={src} alt="image of ggoggam" width={512} height={512}></Image>
                  </CardContent>
                </Card>
              </div>
            </CarouselItem>
          ))}
        </CarouselContent>
        <CarouselPrevious />
        <CarouselNext />
        </Carousel>
      </div>
    </div>
    
  )
}
