// src/lib/components/site-footer.svelte
<script lang="ts">
	import { siteConfig } from "$lib/config";
</script>

<footer>
	<div class="container flex flex-col items-center justify-between sm:h-24">
        <p class="text-sm leading-loose text-muted-foreground md:text-left">
            Built with
            <a
                href="https://www.shadcn-svelte.com"
                target="_blank"
                rel="noreferrer"
                class="font-medium underline underline-offset-4"
            >
                shadcn-svelte
        </a>
        </p>
	</div>
</footer>

// src/components/site/site-footer.tsx
export type SiteFooterProps = {
  github: string;
  source: string;
};

export default function SiteFooter({ github, source }: SiteFooterProps) {
  return (
    <div className="font-mono max-w-2xl w-full mx-auto px-6 py-8 text-sm text-gray-400 flex items-center justify-between">
      <p>&copy; {new Date().getFullYear()} ggoggam</p>
      <div className="flex gap-4">
        <a href={github} target="_blank" rel="noopener noreferrer">
          github
        </a>
        <a href={source} target="_blank" rel="noopener noreferrer">
          source
        </a>
      </div>
    </div>
  );
}
