// app/about/page.tsx
export default function TodayILearnedPage() {
    return <div className="flex flex-col py-4 space-y-4 max-w-3xl mx-auto">
      <h3 className="text-4xl font-bold">about</h3>
      <p>I am a self-learner with interests ranging from user interface / experience, backend, to artificial intelligence. Here, I am sharing my insights from my past-time tinkerings and readings.</p>
      <p>I occassionally research on topics in artificial intelligence (that is not necessarily related to large language models). I am currently based in Seoul, Korea with my black cat named ggoggam. You can contact me via Github.</p>
    </div>
}

// src/routes/about/+page.svelte
<script>
    import { siteConfig } from "$lib/config"
</script>

<svelte:head>
    <title>{siteConfig.name} - about</title>
</svelte:head>

<div class="max-w-2xl self-center">
    <div class="flex flex-col gap-y-6">
        <h1 class="text-2xl font-semibold flex flex-grow">
            About Me
        </h1>
        <p class="leading-relaxed text-base text-wrap">
            I am a self-learner with interests ranging from user interface / experience, backend, to artificial intelligence. 
            Here, I am sharing my insights from my past-time tinkerings and readings. 
        </p>
        <p class="leading-relaxed text-base text-wrap">
            I occassionally research on topics in artificial intelligence (that is not necessarily related to large language models).
            I am currently based in Seoul, Korea with my black cat named ggoggam. 
            You can contact me via <a href="https://www.github.com/ggoggam" class="underline">Github</a>.
        </p>
    </div>
</div>
